# Generated by Django 3.0.8 on 2020-08-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessertpic',
            name='name_1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mainpic',
            name='name_1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='starterpic',
            name='name_1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
