# Generated by Django 3.0.8 on 2020-09-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_restaurant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restLat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restLng',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
