# Generated by Django 3.0.8 on 2020-09-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200921_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='adress',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
