# Generated by Django 3.0.8 on 2020-09-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200912_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
