# Generated by Django 3.0.8 on 2020-09-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200912_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessertpic',
            name='lat_pic_1',
        ),
        migrations.RemoveField(
            model_name='dessertpic',
            name='lng_pic_1',
        ),
        migrations.RemoveField(
            model_name='dessertpic',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='dessertpic',
            name='shot_time_1',
        ),
        migrations.RemoveField(
            model_name='insidepic',
            name='lat_pic_1',
        ),
        migrations.RemoveField(
            model_name='insidepic',
            name='lng_pic_1',
        ),
        migrations.RemoveField(
            model_name='insidepic',
            name='shot_time_1',
        ),
        migrations.RemoveField(
            model_name='mainpic',
            name='lat_pic_1',
        ),
        migrations.RemoveField(
            model_name='mainpic',
            name='lng_pic_1',
        ),
        migrations.RemoveField(
            model_name='mainpic',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='mainpic',
            name='shot_time_1',
        ),
        migrations.RemoveField(
            model_name='menupic',
            name='lat_pic_1',
        ),
        migrations.RemoveField(
            model_name='menupic',
            name='lng_pic_1',
        ),
        migrations.RemoveField(
            model_name='menupic',
            name='shot_time_1',
        ),
        migrations.RemoveField(
            model_name='outsidepic',
            name='lat_pic_1',
        ),
        migrations.RemoveField(
            model_name='outsidepic',
            name='lng_pic_1',
        ),
        migrations.RemoveField(
            model_name='outsidepic',
            name='shot_time_1',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='website',
        ),
        migrations.RemoveField(
            model_name='starterpic',
            name='lat_pic_1',
        ),
        migrations.RemoveField(
            model_name='starterpic',
            name='lng_pic_1',
        ),
        migrations.RemoveField(
            model_name='starterpic',
            name='shot_time_1',
        ),
    ]
