# Generated by Django 3.0.6 on 2020-07-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200719_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starterpics',
            options={'verbose_name': 'StarterPics', 'verbose_name_plural': 'StarterPics'},
        ),
    ]
