# Generated by Django 3.0.6 on 2020-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200719_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessertpics',
            options={'verbose_name': 'DessertPics', 'verbose_name_plural': 'DessertPics'},
        ),
        migrations.AlterModelOptions(
            name='insidepics',
            options={'verbose_name': 'InsidePics', 'verbose_name_plural': 'InsidePics'},
        ),
        migrations.AlterModelOptions(
            name='mainpics',
            options={'verbose_name': 'MainPics', 'verbose_name_plural': 'MainPics'},
        ),
        migrations.AlterModelOptions(
            name='menupics',
            options={'verbose_name': 'MenuPics', 'verbose_name_plural': 'MenuPics'},
        ),
        migrations.AlterModelOptions(
            name='outsidepics',
            options={'verbose_name': 'OutsidePics', 'verbose_name_plural': 'OutsidePics'},
        ),
        migrations.AlterField(
            model_name='dessertpics',
            name='name_1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='dessertpics',
            name='name_2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mainpics',
            name='name_1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mainpics',
            name='name_2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='starterpics',
            name='name_1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='starterpics',
            name='name_2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
