# Generated by Django 3.0.8 on 2020-07-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20200720_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maps_id', models.CharField(max_length=140)),
                ('adress', models.CharField(max_length=240)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='name',
        ),
        migrations.AlterField(
            model_name='dessertpics',
            name='maps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.RestaurantId'),
        ),
        migrations.AlterField(
            model_name='insidepics',
            name='maps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.RestaurantId'),
        ),
        migrations.AlterField(
            model_name='mainpics',
            name='maps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.RestaurantId'),
        ),
        migrations.AlterField(
            model_name='menupics',
            name='maps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.RestaurantId'),
        ),
        migrations.AlterField(
            model_name='outsidepics',
            name='maps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.RestaurantId'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='maps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.RestaurantId'),
        ),
        migrations.AlterField(
            model_name='starterpics',
            name='maps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.RestaurantId'),
        ),
    ]
