# Generated by Django 3.0.8 on 2020-07-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20200720_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantid',
            name='maps_id',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
