# Generated by Django 3.0.8 on 2020-07-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20200720_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starterpics',
            name='restaurant_review_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='places.RestaurantReview'),
        ),
    ]
