# Generated by Django 3.0.8 on 2020-07-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20200720_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessertpics',
            old_name='maps_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='insidepics',
            old_name='maps_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='mainpics',
            old_name='maps_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='menupics',
            old_name='maps_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='outsidepics',
            old_name='maps_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='restaurantreview',
            old_name='maps_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='starterpics',
            old_name='maps_id',
            new_name='restaurant_id',
        ),
    ]
